name: Generate and Deploy JavaDoc

on:
  push:
    branches:
      - 4.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/javaDoc
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 à quoi sert cette action
